export const SET_BANNER_VIEW = 'SET_BANNER_VIEW';
export const SET_MENU_VIEW = 'SET_CONTACT_VIEW';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_FAILURE = 'EMAIL_FAILURE';
export const APPLICATION_SUCCESS = 'APPLICATION_SUCCESS';
export const APPLICATION_FAILURE = 'APPLICATION_FAILURE';
export const REDIRECT_ON_SUCCESS = 'REDIRECT_ON_SUCCESS';
